apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8srequiredReplicas
metadata:
  name: must-have-min-3-replicaset
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    message: "Deployment should have min 3 replicaset"