apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8srequiredReplicas
metadata:
  name: must-have-min-3-replicaset
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    replicaset: 3