apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredreplicas
  annotations:
    description: Enforcing replica numbers to have minimun values
spec:
  crd:
    spec:
      names:
        kind: k8srequiredReplicas
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            replicaset:
              type: number

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredReplicas
        
        deny[msg] {
          
          provided := input.review.object.spec.replicas
          required := input.parameters.replicaset
          required - provided > 0
          msg := sprintf("you must provide minimum : %v replicas", [required])
        }
         deny[msg] {
          input.review.object != "Deployment"
          msg := sprintf("Please select only kind: Deployment",[])
        }