apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredreplicas
  annotations:
    description: Enforcing replica numbers to have minimun values
spec:
  crd:
    spec:
      names:
        kind: k8srequiredReplicas
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            message:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredReplicas

        violation[{"msg": msg, "details": {}}] {
          provided := input.review.object.spec.replicas
          provided < 3
          msg :=  input.parameter.message
        }
         violation[{"msg": msg, "details": {}}] {
          input.review.object.kind != "Deployment"
          msg := input.parameter.message
        }